test: &default

  # Credentials for REST APIs
  client_id: AZ6o1xD9n-Gs2rNvnOqAJDy7u5I-fKOBxkJeHfNYf1pSS4hDB-U8gcPj0FiR
  client_secret: EMEdRhBLHU6PQ-l7mE3ml2MeSHsZEtYKi_sznyD-_T8BzeCSpCKBNXHgGPU7

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: Paperclip
  username: fabio.petrucci-facilitator_api1.gmail.com
  password: 1403515514
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31Aw85uHrK8bE0-Jk.WBSJASz1va0m
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: fabio.petrucci-facilitator_api1.gmail.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live
