#User.new(:email => "fabio.petrucci@gmail.com", :encrypted_password => "$2a$10$/kiVWg1o/vcw2spI2EsMPOzCHYF.kVmRJc1m4lIyT2eSFNQ925c8i", :admin => true).save(:validate => false)
Service.create!(:id => 1, :name => 'Paperclip Single')
Service.create!(:id => 2, :name => 'Paperclip Net')
Service.create!(:id => 3, :name => 'Paperclip Cloud')
Plan.create!(:service_id => 1, :name => "Trimestrale", :months => 3, :price => 27, :discount => nil)
Plan.create!(:service_id => 1, :name => "Semestrale", :months => 6, :price => 54, :discount => 5)
Plan.create!(:service_id => 1, :name => "Annuale", :months => 12, :price => 108, :discount => 10)
Plan.create!(:service_id => 2, :name => "Trimestrale", :months => 3, :price => 117, :discount => nil)
Plan.create!(:service_id => 2, :name => "Semestrale", :months => 6, :price => 234, :discount => 5)
Plan.create!(:service_id => 2, :name => "Annuale", :months => 12, :price => 468, :discount => 10)
Plan.create!(:service_id => 3, :name => "Trimestrale", :months => 3, :price => 177, :discount => nil)
Plan.create!(:service_id => 3, :name => "Semestrale", :months => 6, :price => 354, :discount => 5)
Plan.create!(:service_id => 3, :name => "Annuale", :months => 12, :price => 708, :discount => 10)
Vat.create!(:description => 'Aliquota 22%', :percentage => 22.0, :predefined => false, :active => true)
Vat.create!(:description => "Art. 27 c. 1 e 2 D.L. 6.7.2011 n. 98.", :percentage => 0, :predefined => true, :active => true)
InvoiceNote.create(:description => "- Operazione effettuata ai sensi dell'articolo 27 commi 1 e 2 D.L. 6 luglio 2011 n. 98", :active => true)
InvoiceNote.create(:description => "- Imposta di bollo assolta ai sensi dell'art. 13 della Tariffa allegata al DPR 26.10.71 n. 642.", :active => true)
InvoiceNote.create(:description => "- Prestazione non soggetta a ritenuta d'acconto ai sensi del comma 5.2 del Provvedimento Agenzia delle entrate del 22.12.2011 n. 185820", :active => true)
